from App.dashApps.Groundwater.unitHydrograph.callbacks.hydrograph_tab import callback___hydrograph_tab___unitHydrograph___groundwater


def callback___unitHydrograph___groundwater(app):
    callback___hydrograph_tab___unitHydrograph___groundwater(app=app)